name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]  # Una volta al giorno a mezzanotte (UTC)
  workflow_dispatch:              # Permette di eseguirlo manualmente

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: LaMinerva
          template: classic
          base: header, repositories
          config_timezone: Europe/Rome

          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_indepth: yes
          plugin_languages_limit: 10
