name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]  
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          
          token: ${{ secrets.METRICS_TOKEN }}

          
          filename: github-metrics.svg
          committer_branch: main
          committer_message: "chore: update metrics"

          
          user: LaMinerva
          template: classic
          base: header, repositories
          config_timezone: Europe/Rome

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_indepth: yes
          plugin_languages_limit: 10


      #2
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: languages.svg
          committer_branch: main
          committer_message: "chore: update languages chart"
          user: LaMinerva
          template: classic
          base: ""
          config_timezone: Europe/Rome

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_indepth: yes
          plugin_languages_limit: 10

